[platformio]
default_envs = sirith_tetra_esp32s3

[env:sirith_tetra_esp32s3]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_extra_dirs = ../../lib
build_flags =
  -DMMPR_FW_VERSION=\"0.1.0\"
