[platformio]
default_envs = sirith_tetra_pico_w_rp2040

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../lib
build_flags =
  -DMMPR_FW_VERSION=\"0.1.0\"

[env:sirith_tetra_pico_w_rp2040]
board = rpipicow
board_build.core = earlephilhower

[env:sirith_tetra_pico2_w_rp2350]
board = rpipico2w
board_build.core = earlephilhower
