[platformio]
default_envs = point_esp32

[env:point_esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_extra_dirs = ../../lib
build_flags =
  -DMMPR_FW_VERSION=\"0.1.0\"
